# Generated by Django 3.0.3 on 2020-02-29 22:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Einreichung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('kuenstler', models.CharField(max_length=200, verbose_name='Künstler')),
                ('dauer', models.IntegerField(default=0, verbose_name='Dauer')),
                ('link', models.CharField(max_length=200, validators=[django.core.validators.URLValidator(schemes=['https', 'http'])], verbose_name='Link')),
                ('thumbnail', models.CharField(max_length=100, verbose_name='Thumbnail')),
                ('status', models.CharField(choices=[('wait', 'Auf Überprüfung warten...'), ('playlist', 'In der Playlist'), ('play', 'Spielt gerade'), ('passed', 'Schon vorbei'), ('forbidden', 'Wurde nicht zugelassen')], default='wait', max_length=20, verbose_name='Status')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Hinzugefügt am')),
                ('starttimestamp', models.DateTimeField(auto_now_add=True, verbose_name='Gestartet um')),
                ('endtimestamp', models.DateTimeField(auto_now_add=True, verbose_name='Endet um')),
                ('benutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Einreichung',
                'verbose_name_plural': 'Einreichungen',
            },
        ),
    ]
